apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: customer-wordpress
secretGenerator:
- name: mysql-pass
  literals:
  - password=12345
resources:
 - namespace.yaml
 - mysql-deployment.yaml
 - wordpress-deployment.yaml
